### ISSUE TITLE
Styling issue in Firefox 49 MacOS

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing.io#138] opened 2016-10-22 18:51 UTC
I am seeing a white horizontal bar at the top of the page, as in the screenshot below.  Playing with the Inspector, it seems to be coming from section class="hero landing-page" and goes away of I change margin-top on `.hero` from -80px to -90px.

![screen shot 2016-10-22 at 2 48 09 pm](https://cloud.githubusercontent.com/assets/3523016/19621751/9a22ba60-9866-11e6-8046-3f7b876082e0.png)

@reimertz

**Comment by reimertz** [comment] 2016-10-22 19:14
it's because of the mailing-list button we added later in the project. Will add a media query that simple hides the button if the width of the site is to small. Thanks for catching this @yurishkuro!

**Comment by reimertz** [comment] 2016-10-22 19:20
fixed by #139

**Comment by yurishkuro** [comment] 2016-10-22 23:28
btw, the issue I had was on a macbook air

**Comment by yurishkuro** [comment] 2016-10-23 02:55
#139 did not fix this issue

**Comment by reimertz** [comment] 2016-10-23 13:18
that is weird, the issues are gone on for me, tested all major resolutions and resized window. I guess i'll have to boot up my old air to see if I can reproduce it. 

Do you see this on opentracing.io as well?

**Comment by yurishkuro** [comment] 2016-10-23 21:27
yes, but only in firefox

**Comment by tedsuo** [comment] 2018-10-11 16:21
Appears fixed. Also, we'll be redesigning the site soon.

**Closed by tedsuo** 2018-10-11 16:21 UTC
